language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
services:
  - postgresql

before_script:
  - psql -c "create database testbd;" -U postgres
  - psql -c "ALTER  postgres WITH PASSWORD 5454Support54"
script:
  - nosetests
  - nosetests --with-coverage --cover-erase --cover-package=app --cover-package=tests

after_sucess:
  - "coveralls"

# whitelist   
branches:
  only:
    - master

notifications:  # specify build notifications
  email:
    - sam.achola@live.com
on_success: change
on_failure: always
