language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - 

after_sucess:
  - "coveralls"

# whitelist   
branches:
  only:
    - master

notifications:  # specify build notifications
  email:
    - sam.achola@live.com
on_success: change
on_failure: always
