"""empty message

Revision ID: 11a599b0d6bd
Revises: 5e70aa7492a6
Create Date: 2018-01-10 18:32:24.128252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11a599b0d6bd'
down_revision = '5e70aa7492a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'recipes', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipes', type_='foreignkey')
    # ### end Alembic commands ###
