"""empty message

Revision ID: 2abfade57ce9
Revises: 11a599b0d6bd
Create Date: 2018-01-30 17:12:23.161462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2abfade57ce9'
down_revision = '11a599b0d6bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'admin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('admin', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
